# Generated by Django 5.2.8 on 2025-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoredpage",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("minute", "Minutes"),
                    ("hour", "Hours"),
                    ("day", "Days"),
                    ("week", "Weeks"),
                    ("month", "Months"),
                    ("year", "Years"),
                ],
                max_length=10,
            ),
        ),
    ]
