# Generated by Django 5.2.8 on 2025-11-17 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_monitoredpage_frequency_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredpage',
            name='last_content',
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
