# Generated by Django 5.2.8 on 2025-11-17 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_monitoredpage_frequency_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredpage',
            name='last_content',
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('monitored_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.monitoredpage')),
            ],
        ),
    ]
