# Generated by Django 5.2.8 on 2025-11-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_pagesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='last_seen_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.pagesnapshot'),
        ),
    ]
